// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// Code Updated by Vasant and Mohnish

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuBnfQgIMUr_IL6IVuXeZUM3rCeGhsvyY',
    appId: '1:729752416660:web:b85101463630d0d0c61f81',
    messagingSenderId: '729752416660',
    projectId: 'c-client-registration',
    authDomain: 'c-client-registration.firebaseapp.com',
    storageBucket: 'c-client-registration.appspot.com',
    measurementId: 'G-60J6YZ9B4L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkMcVb4ZeWHxmDFp6YJ97E3OWQmxAMANE',
    appId: '1:729752416660:android:6230288fa41c2148c61f81',
    messagingSenderId: '729752416660',
    projectId: 'c-client-registration',
    storageBucket: 'c-client-registration.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2kwpHN_XqzCxuc-RzhlCaujqdN4i29FQ',
    appId: '1:729752416660:ios:7b06d86d90e210c2c61f81',
    messagingSenderId: '729752416660',
    projectId: 'c-client-registration',
    storageBucket: 'c-client-registration.appspot.com',
    iosClientId:
        '729752416660-hvvs6kaj3vft6pks2shk7o2e87q2jn7i.apps.googleusercontent.com',
    iosBundleId: 'com.example.craveiospro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2kwpHN_XqzCxuc-RzhlCaujqdN4i29FQ',
    appId: '1:729752416660:ios:7b06d86d90e210c2c61f81',
    messagingSenderId: '729752416660',
    projectId: 'c-client-registration',
    storageBucket: 'c-client-registration.appspot.com',
    iosClientId:
        '729752416660-hvvs6kaj3vft6pks2shk7o2e87q2jn7i.apps.googleusercontent.com',
    iosBundleId: 'com.example.craveiospro',
  );
}
